const generateDate = (daysToAdd: number) => {
  const now = new Date();
  now.setDate(now.getDate() + daysToAdd);
  return now;
};

export const data = {
  todos: [
    {
      id: 1,
      title: "Do something nice for someone you care about",
      completed: false,
      dueDate: generateDate(120).toISOString(),
      priority: "high",
    },
    {
      id: 2,
      title: "Memorize a poem",
      completed: true,
      dueDate: "2024-08-10T15:45:00",
      priority: "medium",
      completedAt: "2024-07-10T15:45:00",
    },
    {
      id: 3,
      title: "Watch a classic movie",
      completed: false,
      dueDate: generateDate(40).toISOString(),
      priority: "low",
    },
    {
      id: 4,
      title: "Watch a documentary",
      completed: false,
      dueDate: generateDate(60).toISOString(),
      priority: "high",
    },
    {
      id: 5,
      title: "Invest in cryptocurrency",
      completed: false,
      dueDate: generateDate(100).toISOString(),
      priority: "medium",
    },
    {
      id: 6,
      title:
        "Contribute code or a monetary donation to an open-source software project",
      completed: false,
      dueDate: generateDate(300).toISOString(),
      priority: "low",
    },
    {
      id: 7,
      title: "Solve a Rubik's cube",
      completed: true,
      dueDate: "2024-09-15T10:32:00",
      priority: "high",
      completedAt: "2024-09-14T10:32:00",
    },
    {
      id: 8,
      title: "Bake pastries for yourself and neighbor",
      completed: false,
      dueDate: generateDate(20).toISOString(),
      priority: "medium",
    },
    {
      id: 9,
      title: "Go see a Broadway production",
      completed: false,
      dueDate: generateDate(90).toISOString(),
      priority: "low",
    },
    {
      id: 10,
      title: "Write a thank you letter to an influential person in your life",
      completed: true,
      dueDate: "2024-12-15T11:07:00",
      priority: "high",
      completedAt: "2024-12-14T11:07:00",
    },
    {
      id: 11,
      title: "Invite some friends over for a game night",
      completed: false,
      dueDate: generateDate(200).toISOString(),
      priority: "medium",
    },
    {
      id: 12,
      title: "Have a football scrimmage with some friends",
      completed: false,
      dueDate: generateDate(180).toISOString(),
      priority: "low",
    },
    {
      id: 13,
      title: "Text a friend you haven't talked to in a long time",
      completed: true,
      dueDate: "2024-10-05T17:21:00",
      priority: "high",
      completedAt: "2024-10-04T17:21:00",
    },
    {
      id: 14,
      title: generateDate(99).toISOString(),
      completed: false,
      dueDate: "2025-01-31T14:48:00",
      priority: "medium",
    },
    {
      id: 15,
      title: "Buy a new house decoration",
      completed: false,
      dueDate: generateDate(50).toISOString(),
      priority: "low",
    },
    {
      id: 16,
      title: "Plan a vacation you've always wanted to take",
      completed: true,
      dueDate: "2024-11-01T05:29:00",
      priority: "high",
      completedAt: "2024-10-31T05:29:00",
    },
    {
      id: 17,
      title: "Clean out car",
      completed: false,
      dueDate: generateDate(300).toISOString(),
      priority: "medium",
    },
    {
      id: 18,
      title: "Draw and color a Mandala",
      completed: true,
      dueDate: "2024-10-30T22:03:00",
      priority: "low",
      completedAt: "2024-10-29T22:03:00",
    },
    {
      id: 19,
      title: "Create a cookbook with favorite recipes",
      completed: true,
      dueDate: "2024-12-05T17:26:00",
      priority: "high",
      completedAt: "2024-12-04T17:26:00",
    },
    {
      id: 20,
      title: "Bake a pie with some friends",
      completed: false,
      dueDate: generateDate(70).toISOString(),
      priority: "medium",
    },
    {
      id: 21,
      title: "Create a compost pile",
      completed: false,
      dueDate: generateDate(250).toISOString(),
      priority: "low",
    },
    {
      id: 22,
      title: "Take a hike at a local park",
      completed: false,
      dueDate: "2024-09-30T17:43:00",
      priority: "high",
    },
    {
      id: 23,
      title: "Take a class at local community center that interests you",
      completed: true,
      dueDate: "2024-11-15T14:09:00",
      priority: "medium",
      completedAt: "2024-11-14T14:09:00",
    },
    {
      id: 24,
      title: "Research a topic interested in",
      completed: false,
      dueDate: generateDate(30).toISOString(),
      priority: "low",
    },
    {
      id: 25,
      title: "Plan a trip to another country",
      completed: false,
      dueDate: generateDate(150).toISOString(),
      priority: "high",
    },
    {
      id: 26,
      title: "Improve touch typing",
      completed: false,
      dueDate: generateDate(220).toISOString(),
      priority: "medium",
    },
    {
      id: 27,
      title: "Learn Express.js",
      completed: false,
      dueDate: generateDate(160).toISOString(),
      priority: "low",
    },
    {
      id: 28,
      title: "Learn calligraphy",
      completed: false,
      dueDate: generateDate(180).toISOString(),
      priority: "high",
    },
    {
      id: 29,
      title: "Have a photo session with some friends",
      completed: true,
      dueDate: "2024-12-20T00:19:00",
      priority: "medium",
      completedAt: "2024-12-19T00:19:00",
    },
    {
      id: 30,
      title: "Go to the gym",
      completed: false,
      dueDate: "2024-11-05T18:36:00",
      priority: "low",
    },
  ],
};
